### PR TITLE
Question_10

### PR DESCRIPTION
**Pull request by bhfowler**

### CODE REVIEW

**Comment by bhfowler** [comment]
Guys, I made a mistake. #10 should have assigned to Caroline. Sorry both

**Review by bladealec — COMMENTED** [review]
I don't think the CTE you created was necessary, and I don't think you could filter for max homeruns any better way than you did. You could have created a totally separate table but I'm not sure if that would save on processing power for this application. Your output seems to be correct though.

The code below shows how you can get the same output without the CTE.
WITH player_list AS (
	SELECT 
		playerid 
		,namefirst 
		,namelast 
		,debut 
	FROM people 
	WHERE 
		debut::DATE > '2006-01-01')

SELECT 
	playerid 
	,player_list.namefirst AS first_name
	,namelast AS last_name
	,batting.hr AS home_run
FROM batting
	INNER JOIN player_list
		USING(playerid)
WHERE 
	(playerid, hr) IN (
		SELECT
			playerid 
			,MAX(hr)
		FROM batting
		GROUP BY playerid
		HAVING MAX(hr)> 0 )
	AND yearid = 2016

**Comment by bhfowler** [comment]
I tend to create unnecessary CTE, thinking it helps to make my code more readable.
Prob not a good enough reason to justify performance degradation.

Thank you for your review.

**Review by bladealec — APPROVED** [review]

**Comment by bhfowler** [comment]
I fixed the problem.
Thank you, Caroline!

**Pull request closed without merging**
